import { v4 as uuidv4 } from 'uuid';
import type { TicketEvent, Ticket, TicketAction, TicketTemplate, DashboardStats } from '@/types';
import { generateQrHash } from './utils';

// ─── Helpers ────────────────────────────────────────────────────────

const generateWallet = () => `0x${Array.from({ length: 40 }, () => Math.floor(Math.random() * 16).toString(16)).join('')}`;
const generateDate = (daysFromNow: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString();
};
const pastDate = (daysAgo: number) => generateDate(-daysAgo);

// ─── Templates ──────────────────────────────────────────────────────

export const demoTemplates: TicketTemplate[] = [
  {
    id: 'tmpl-event-v1',
    name: 'dual-tickets::event-ticket::v1',
    version: '1.0.0',
    fields: [
      { name: 'eventName', type: 'string', required: true },
      { name: 'eventDate', type: 'string', required: true },
      { name: 'venue', type: 'string', required: true },
      { name: 'seatInfo', type: 'string', required: false },
      { name: 'purchasePrice', type: 'number', required: true },
      { name: 'currentPrice', type: 'number', required: true },
      { name: 'status', type: 'enum', required: true },
      { name: 'qrCode', type: 'string', required: true },
    ],
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'tmpl-experience-v1',
    name: 'dual-tickets::experience-ticket::v1',
    version: '1.0.0',
    fields: [
      { name: 'eventName', type: 'string', required: true },
      { name: 'eventDate', type: 'string', required: true },
      { name: 'venue', type: 'string', required: true },
      { name: 'purchasePrice', type: 'number', required: true },
      { name: 'currentPrice', type: 'number', required: true },
      { name: 'status', type: 'enum', required: true },
      { name: 'qrCode', type: 'string', required: true },
    ],
    createdAt: '2026-01-15T10:00:00Z',
  },
];

// ─── Events ─────────────────────────────────────────────────────────

export const demoEvents: TicketEvent[] = [
  {
    id: 'evt-001',
    name: 'Vivid Sydney 2026 — Opening Night',
    type: 'festival',
    category: 'arts',
    venue: { name: 'Sydney Opera House', address: 'Bennelong Point', city: 'Sydney', country: 'Australia', capacity: 5000 },
    date: { start: generateDate(14), end: generateDate(14), doors: generateDate(14) },
    description: 'Experience the spectacular opening night of Vivid Sydney with immersive light projections on the Opera House sails, live electronic music, and rooftop viewing areas.',
    imageUrl: 'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?w=1000&h=667&fit=crop',
    organizerId: 'org-vivid-events',
    tiers: [
      { id: 'tier-001-ga', name: 'General Admission', price: 45, capacity: 3000, sold: 2847, description: 'Entry to all public viewing areas', perks: ['Access to light installations', 'Food court access'] },
      { id: 'tier-001-vip', name: 'VIP Lounge', price: 195, capacity: 500, sold: 489, description: 'Premium rooftop viewing with complimentary drinks', perks: ['Rooftop viewing deck', 'Complimentary drinks', 'Priority entry', 'VIP lounge access'] },
      { id: 'tier-001-back', name: 'Backstage Experience', price: 450, capacity: 50, sold: 50, description: 'Go behind the scenes with the creative team', perks: ['Meet the artists', 'Behind-the-scenes tour', 'Signed poster', 'VIP perks included'] },
    ],
    status: 'on-sale',
    resaleEnabled: true,
    resaleMaxMarkup: 1.5,
    createdAt: pastDate(30),
    updatedAt: pastDate(2),
  },
  {
    id: 'evt-002',
    name: 'Tame Impala — World Tour 2026',
    type: 'concert',
    category: 'music',
    venue: { name: 'Qudos Bank Arena', address: 'Olympic Blvd, Sydney Olympic Park', city: 'Sydney', country: 'Australia', capacity: 21000 },
    date: { start: generateDate(28), end: generateDate(28), doors: generateDate(28) },
    description: 'Tame Impala returns to Sydney for a monumental arena show. Full production with cutting-edge visuals, confetti cannons, and an extended set list spanning their entire catalogue.',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1000&h=667&fit=crop',
    organizerId: 'org-live-nation',
    tiers: [
      { id: 'tier-002-ga', name: 'General Admission', price: 89, capacity: 15000, sold: 14200, description: 'Standing floor and upper bowl seating', perks: ['Floor or seated entry'] },
      { id: 'tier-002-gold', name: 'Gold Circle', price: 189, capacity: 3000, sold: 2100, description: 'Front-of-stage standing area', perks: ['Front-of-stage access', 'Dedicated bar', 'Fast-track entry'] },
      { id: 'tier-002-plat', name: 'Platinum Suite', price: 450, capacity: 200, sold: 180, description: 'Private suite with catering', perks: ['Private suite', 'Premium catering', 'Dedicated host', 'Merch pack'] },
    ],
    status: 'on-sale',
    resaleEnabled: true,
    resaleMaxMarkup: 1.3,
    createdAt: pastDate(45),
    updatedAt: pastDate(5),
  },
  {
    id: 'evt-003',
    name: 'Sydney FC vs Melbourne Victory — A-League Grand Final',
    type: 'sport',
    category: 'sport',
    venue: { name: 'Accor Stadium', address: 'Olympic Blvd, Sydney Olympic Park', city: 'Sydney', country: 'Australia', capacity: 83500 },
    date: { start: generateDate(7), end: generateDate(7), doors: generateDate(7) },
    description: 'The biggest match of the A-League season. Two fierce rivals battle for the championship in front of a packed stadium under lights.',
    imageUrl: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=1000&h=667&fit=crop',
    organizerId: 'org-football-aus',
    tiers: [
      { id: 'tier-003-ga', name: 'Category C', price: 35, capacity: 40000, sold: 38500, description: 'Upper tier seating', perks: ['Seated entry'] },
      { id: 'tier-003-b', name: 'Category B', price: 75, capacity: 25000, sold: 25000, description: 'Lower tier seating', perks: ['Lower bowl seating', 'Better sightlines'] },
      { id: 'tier-003-a', name: 'Category A', price: 120, capacity: 10000, sold: 9200, description: 'Premium sideline seating', perks: ['Sideline seats', 'Padded seating', 'Cup holders'] },
      { id: 'tier-003-corp', name: 'Corporate Box', price: 850, capacity: 500, sold: 500, description: 'All-inclusive corporate hospitality', perks: ['Private box', 'Full catering', 'Premium bar', 'Parking included'] },
    ],
    status: 'on-sale',
    resaleEnabled: true,
    resaleMaxMarkup: 2.0,
    createdAt: pastDate(60),
    updatedAt: pastDate(1),
  },
  {
    id: 'evt-004',
    name: 'AI & Web3 Summit 2026',
    type: 'conference',
    category: 'tech',
    venue: { name: 'ICC Sydney', address: '14 Darling Dr, Sydney', city: 'Sydney', country: 'Australia', capacity: 3500 },
    date: { start: generateDate(42), end: generateDate(44), doors: generateDate(42) },
    description: 'Three-day conference on the convergence of AI and blockchain technology. Featuring keynotes from industry leaders, hands-on workshops, and networking events.',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1000&h=667&fit=crop',
    organizerId: 'org-tech-events',
    tiers: [
      { id: 'tier-004-std', name: 'Standard Pass', price: 299, capacity: 2500, sold: 1800, description: 'Access to all keynotes and expo floor', perks: ['All keynotes', 'Expo floor', 'Lunch included'] },
      { id: 'tier-004-pro', name: 'Pro Pass', price: 599, capacity: 800, sold: 450, description: 'Standard + all workshops and networking dinner', perks: ['All standard perks', 'Workshop access', 'Networking dinner', 'Recording access'] },
      { id: 'tier-004-vip', name: 'VIP Pass', price: 1499, capacity: 100, sold: 72, description: 'Full access + speaker meet-and-greet + after party', perks: ['All pro perks', 'Speaker lounge', 'VIP after party', 'Priority seating'] },
    ],
    status: 'on-sale',
    resaleEnabled: false,
    resaleMaxMarkup: 1.0,
    createdAt: pastDate(90),
    updatedAt: pastDate(3),
  },
  {
    id: 'evt-005',
    name: 'Coachella 2026 — Weekend 1',
    type: 'festival',
    category: 'music',
    venue: { name: 'Empire Polo Club', address: '81-800 Avenue 51', city: 'Indio', country: 'USA', capacity: 125000 },
    date: { start: generateDate(56), end: generateDate(58), doors: generateDate(56) },
    description: 'The world\'s most iconic music festival returns for Weekend 1. Three days of music, art, and culture in the California desert.',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=1000&h=667&fit=crop',
    organizerId: 'org-goldenvoice',
    tiers: [
      { id: 'tier-005-ga', name: 'General Admission', price: 549, capacity: 100000, sold: 100000, description: 'Full festival access all 3 days', perks: ['3-day access', 'All stages'] },
      { id: 'tier-005-vip', name: 'VIP', price: 1099, capacity: 20000, sold: 19500, description: 'Premium viewing and lounges', perks: ['VIP viewing areas', 'Air-conditioned lounges', 'Premium food vendors', 'Dedicated entry'] },
      { id: 'tier-005-saf', name: 'Safari Camping', price: 9500, capacity: 200, sold: 200, description: 'Luxury on-site glamping', perks: ['Luxury tent', 'Private showers', 'Concierge service', 'All VIP perks'] },
    ],
    status: 'sold-out',
    resaleEnabled: true,
    resaleMaxMarkup: 1.5,
    createdAt: pastDate(120),
    updatedAt: pastDate(10),
  },
  {
    id: 'evt-006',
    name: 'NBA Finals 2026 — Game 7',
    type: 'sport',
    category: 'sport',
    venue: { name: 'Madison Square Garden', address: '4 Pennsylvania Plaza', city: 'New York', country: 'USA', capacity: 20789 },
    date: { start: generateDate(21), end: generateDate(21), doors: generateDate(21) },
    description: 'The ultimate decider. Game 7 of the NBA Finals at the world\'s most famous arena. Basketball history will be made tonight.',
    imageUrl: 'https://images.unsplash.com/photo-1504450758481-7338bbe75005?w=1000&h=667&fit=crop',
    organizerId: 'org-nba',
    tiers: [
      { id: 'tier-006-upper', name: 'Upper Level', price: 350, capacity: 10000, sold: 10000, description: 'Upper bowl seating', perks: ['Seated entry'] },
      { id: 'tier-006-lower', name: 'Lower Level', price: 1200, capacity: 8000, sold: 8000, description: 'Lower bowl seating', perks: ['Premium sightlines', 'Club access'] },
      { id: 'tier-006-court', name: 'Courtside', price: 15000, capacity: 200, sold: 200, description: 'Courtside seats', perks: ['Courtside seating', 'Player tunnel access', 'Premium catering', 'Gift bag'] },
    ],
    status: 'sold-out',
    resaleEnabled: true,
    resaleMaxMarkup: 3.0,
    createdAt: pastDate(90),
    updatedAt: pastDate(1),
  },
  // ─── Experiences ────────────────────────────────────────────────
  {
    id: 'evt-007',
    name: 'Hunter Valley Wine & Cheese Masterclass',
    type: 'experience',
    category: 'food-wine',
    venue: { name: 'Tyrrell\'s Wines', address: '1838 Broke Rd', city: 'Hunter Valley', country: 'Australia', capacity: 30 },
    date: { start: generateDate(10), end: generateDate(10) },
    description: 'An intimate afternoon with Master of Wine Sarah Andrew. Taste six premium vintages paired with artisan cheeses from local producers. Includes a signed bottle to take home.',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=1000&h=667&fit=crop',
    organizerId: 'org-wine-experiences',
    tiers: [
      { id: 'tier-007-std', name: 'Standard Tasting', price: 150, capacity: 20, sold: 18, description: '6-wine tasting with cheese board', perks: ['6 premium wines', 'Artisan cheese board', 'Tasting notes booklet'] },
      { id: 'tier-007-prem', name: 'Premium + Bottle', price: 295, capacity: 10, sold: 8, description: 'Tasting + signed rare vintage bottle', perks: ['All standard perks', 'Signed bottle of Tyrrell\'s Vat 1 Semillon', 'Winery cellar tour'] },
    ],
    status: 'on-sale',
    resaleEnabled: false,
    resaleMaxMarkup: 1.0,
    createdAt: pastDate(20),
    updatedAt: pastDate(3),
  },
  {
    id: 'evt-008',
    name: 'Sunrise Yoga on Bondi Beach',
    type: 'experience',
    category: 'wellness',
    venue: { name: 'Bondi Beach Pavilion', address: 'Queen Elizabeth Dr', city: 'Sydney', country: 'Australia', capacity: 50 },
    date: { start: generateDate(3), end: generateDate(3) },
    description: 'Greet the dawn with a guided yoga session on the sand at Bondi Beach. Includes a post-session smoothie bowl and meditation workshop.',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=1000&h=667&fit=crop',
    organizerId: 'org-wellness-co',
    tiers: [
      { id: 'tier-008-ga', name: 'Yoga + Smoothie', price: 35, capacity: 40, sold: 32, description: '90-min session with organic smoothie bowl', perks: ['Guided yoga session', 'Organic smoothie bowl', 'Yoga mat provided'] },
      { id: 'tier-008-prem', name: 'Yoga + Meditation + Brunch', price: 85, capacity: 10, sold: 7, description: 'Extended session with meditation and beachside brunch', perks: ['All standard perks', '30-min guided meditation', 'Beachside brunch'] },
    ],
    status: 'on-sale',
    resaleEnabled: false,
    resaleMaxMarkup: 1.0,
    createdAt: pastDate(10),
    updatedAt: pastDate(1),
  },
  {
    id: 'evt-009',
    name: 'Blue Mountains Sunset Helicopter Tour',
    type: 'experience',
    category: 'adventure',
    venue: { name: 'Blue Mountains Helipad', address: 'Great Western Hwy', city: 'Katoomba', country: 'Australia', capacity: 12 },
    date: { start: generateDate(18), end: generateDate(18) },
    description: 'Soar above the Three Sisters and Jamison Valley at golden hour. A 45-minute scenic flight with champagne toast upon landing.',
    imageUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1000&h=667&fit=crop',
    organizerId: 'org-adventure-aus',
    tiers: [
      { id: 'tier-009-std', name: 'Scenic Flight', price: 350, capacity: 8, sold: 6, description: '45-min helicopter flight over the Blue Mountains', perks: ['45-min scenic flight', 'Professional pilot commentary', 'Photo opportunities'] },
      { id: 'tier-009-prem', name: 'Flight + Champagne Picnic', price: 650, capacity: 4, sold: 3, description: 'Flight + private champagne sunset picnic', perks: ['All standard perks', 'Champagne picnic at private lookout', 'Professional photographer'] },
    ],
    status: 'on-sale',
    resaleEnabled: false,
    resaleMaxMarkup: 1.0,
    createdAt: pastDate(15),
    updatedAt: pastDate(2),
  },
  {
    id: 'evt-010',
    name: 'Completed: Ed Sheeran — Mathematics Tour',
    type: 'concert',
    category: 'music',
    venue: { name: 'Accor Stadium', address: 'Olympic Blvd, Sydney Olympic Park', city: 'Sydney', country: 'Australia', capacity: 83500 },
    date: { start: pastDate(14), end: pastDate(14), doors: pastDate(14) },
    description: 'Ed Sheeran delivered an unforgettable performance at a packed Accor Stadium. Solo acoustic sections, full band production, and surprise guest appearances.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1000&h=667&fit=crop',
    organizerId: 'org-live-nation',
    tiers: [
      { id: 'tier-010-ga', name: 'General Admission', price: 120, capacity: 60000, sold: 60000, description: 'Floor standing or upper seating', perks: ['Entry'] },
      { id: 'tier-010-gold', name: 'Gold', price: 250, capacity: 15000, sold: 15000, description: 'Front of stage', perks: ['Front-of-stage', 'Fast entry'] },
    ],
    status: 'completed',
    resaleEnabled: true,
    resaleMaxMarkup: 1.5,
    createdAt: pastDate(180),
    updatedAt: pastDate(14),
  },
];

// ─── Demo wallets ───────────────────────────────────────────────────

const DEMO_CONSUMER_WALLET = '0x742d35Cc6634C0532925a3b844Bc026e6f7D30f0';
const DEMO_ADMIN_WALLET = '0xADMIN0000000000000000000000000000000000';

// ─── Tickets (pre-minted) ───────────────────────────────────────────

export const demoTickets: Ticket[] = [
  // Consumer owns tickets for Vivid, Tame Impala, A-League, Yoga
  {
    id: 'tkt-001',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-vivid-events',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-001',
    tierId: 'tier-001-vip',
    tierName: 'VIP Lounge',
    ticketData: {
      eventName: 'Vivid Sydney 2026 — Opening Night',
      eventDate: demoEvents[0].date.start,
      venue: 'Sydney Opera House',
      purchasePrice: 195,
      currentPrice: 195,
      status: 'valid',
      purchasedAt: pastDate(5),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-001', type: 'image', url: 'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?w=400&h=250&fit=crop' }],
    createdAt: pastDate(5),
    updatedAt: pastDate(5),
    onChainStatus: 'anchored',
  },
  {
    id: 'tkt-002',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-live-nation',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-002',
    tierId: 'tier-002-gold',
    tierName: 'Gold Circle',
    ticketData: {
      eventName: 'Tame Impala — World Tour 2026',
      eventDate: demoEvents[1].date.start,
      venue: 'Qudos Bank Arena',
      purchasePrice: 189,
      currentPrice: 189,
      status: 'valid',
      purchasedAt: pastDate(10),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-002', type: 'image', url: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=400&h=250&fit=crop' }],
    createdAt: pastDate(10),
    updatedAt: pastDate(10),
    onChainStatus: 'anchored',
  },
  {
    id: 'tkt-003',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-football-aus',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-003',
    tierId: 'tier-003-a',
    tierName: 'Category A',
    ticketData: {
      eventName: 'Sydney FC vs Melbourne Victory — A-League Grand Final',
      eventDate: demoEvents[2].date.start,
      venue: 'Accor Stadium',
      seatInfo: 'Section A, Row 12, Seat 5',
      purchasePrice: 120,
      currentPrice: 120,
      status: 'valid',
      purchasedAt: pastDate(3),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-003', type: 'image', url: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=400&h=250&fit=crop' }],
    createdAt: pastDate(3),
    updatedAt: pastDate(3),
    onChainStatus: 'anchored',
  },
  {
    id: 'tkt-004',
    templateId: 'tmpl-experience-v1',
    templateName: 'dual-tickets::experience-ticket::v1',
    organizationId: 'org-wellness-co',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-008',
    tierId: 'tier-008-prem',
    tierName: 'Yoga + Meditation + Brunch',
    ticketData: {
      eventName: 'Sunrise Yoga on Bondi Beach',
      eventDate: demoEvents[7].date.start,
      venue: 'Bondi Beach Pavilion',
      purchasePrice: 85,
      currentPrice: 85,
      status: 'valid',
      purchasedAt: pastDate(2),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-004', type: 'image', url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=250&fit=crop' }],
    createdAt: pastDate(2),
    updatedAt: pastDate(2),
    onChainStatus: 'anchored',
  },
  // A transferred ticket (came from someone else)
  {
    id: 'tkt-005',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-live-nation',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-010',
    tierId: 'tier-010-gold',
    tierName: 'Gold',
    ticketData: {
      eventName: 'Ed Sheeran — Mathematics Tour',
      eventDate: demoEvents[9].date.start,
      venue: 'Accor Stadium',
      purchasePrice: 250,
      currentPrice: 250,
      status: 'used',
      purchasedAt: pastDate(30),
      redeemedAt: pastDate(14),
      transferHistory: [
        { from: generateWallet(), to: DEMO_CONSUMER_WALLET, price: 300, timestamp: pastDate(20), verified: true },
      ],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-005', type: 'image', url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=250&fit=crop' }],
    createdAt: pastDate(30),
    updatedAt: pastDate(14),
    onChainStatus: 'verified',
  },
  // A ticket currently listed for resale
  {
    id: 'tkt-006',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-goldenvoice',
    ownerWallet: generateWallet(),
    eventId: 'evt-005',
    tierId: 'tier-005-ga',
    tierName: 'General Admission',
    ticketData: {
      eventName: 'Coachella 2026 — Weekend 1',
      eventDate: demoEvents[4].date.start,
      venue: 'Empire Polo Club',
      purchasePrice: 549,
      currentPrice: 749,
      status: 'listed',
      purchasedAt: pastDate(60),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-006', type: 'image', url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=250&fit=crop' }],
    createdAt: pastDate(60),
    updatedAt: pastDate(2),
    onChainStatus: 'anchored',
  },
  {
    id: 'tkt-007',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-goldenvoice',
    ownerWallet: generateWallet(),
    eventId: 'evt-005',
    tierId: 'tier-005-vip',
    tierName: 'VIP',
    ticketData: {
      eventName: 'Coachella 2026 — Weekend 1',
      eventDate: demoEvents[4].date.start,
      venue: 'Empire Polo Club',
      purchasePrice: 1099,
      currentPrice: 1499,
      status: 'listed',
      purchasedAt: pastDate(50),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-007', type: 'image', url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=250&fit=crop' }],
    createdAt: pastDate(50),
    updatedAt: pastDate(1),
    onChainStatus: 'anchored',
  },
  {
    id: 'tkt-008',
    templateId: 'tmpl-event-v1',
    templateName: 'dual-tickets::event-ticket::v1',
    organizationId: 'org-nba',
    ownerWallet: generateWallet(),
    eventId: 'evt-006',
    tierId: 'tier-006-lower',
    tierName: 'Lower Level',
    ticketData: {
      eventName: 'NBA Finals 2026 — Game 7',
      eventDate: demoEvents[5].date.start,
      venue: 'Madison Square Garden',
      seatInfo: 'Section 110, Row 8, Seat 3',
      purchasePrice: 1200,
      currentPrice: 3200,
      status: 'listed',
      purchasedAt: pastDate(30),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-008', type: 'image', url: 'https://images.unsplash.com/photo-1504450758481-7338bbe75005?w=400&h=250&fit=crop' }],
    createdAt: pastDate(30),
    updatedAt: pastDate(1),
    onChainStatus: 'anchored',
  },
  // Pending anchor ticket
  {
    id: 'tkt-009',
    templateId: 'tmpl-experience-v1',
    templateName: 'dual-tickets::experience-ticket::v1',
    organizationId: 'org-adventure-aus',
    ownerWallet: DEMO_CONSUMER_WALLET,
    eventId: 'evt-009',
    tierId: 'tier-009-prem',
    tierName: 'Flight + Champagne Picnic',
    ticketData: {
      eventName: 'Blue Mountains Sunset Helicopter Tour',
      eventDate: demoEvents[8].date.start,
      venue: 'Blue Mountains Helipad',
      purchasePrice: 650,
      currentPrice: 650,
      status: 'valid',
      purchasedAt: pastDate(0),
      transferHistory: [],
      qrCode: generateQrHash(),
    },
    faces: [{ id: 'face-tkt-009', type: 'image', url: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=400&h=250&fit=crop' }],
    createdAt: pastDate(0),
    updatedAt: pastDate(0),
    onChainStatus: 'pending',
  },
];

// ─── Actions ────────────────────────────────────────────────────────

export const demoActions: TicketAction[] = [
  { id: uuidv4(), objectId: 'tkt-001', type: 'PURCHASE', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(5), status: 'completed', description: 'Purchased VIP Lounge ticket for Vivid Sydney 2026' },
  { id: uuidv4(), objectId: 'tkt-001', type: 'VERIFY', actor: 'system', timestamp: pastDate(5), status: 'completed', description: 'Ticket anchored to blockchain' },
  { id: uuidv4(), objectId: 'tkt-002', type: 'PURCHASE', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(10), status: 'completed', description: 'Purchased Gold Circle ticket for Tame Impala' },
  { id: uuidv4(), objectId: 'tkt-002', type: 'VERIFY', actor: 'system', timestamp: pastDate(10), status: 'completed', description: 'Ticket anchored to blockchain' },
  { id: uuidv4(), objectId: 'tkt-003', type: 'PURCHASE', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(3), status: 'completed', description: 'Purchased Category A ticket for A-League Grand Final' },
  { id: uuidv4(), objectId: 'tkt-004', type: 'PURCHASE', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(2), status: 'completed', description: 'Purchased Yoga + Meditation + Brunch ticket' },
  { id: uuidv4(), objectId: 'tkt-005', type: 'TRANSFER', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(20), status: 'completed', description: 'Ticket transferred from secondary market' },
  { id: uuidv4(), objectId: 'tkt-005', type: 'REDEEM', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(14), status: 'completed', description: 'Ticket scanned at venue gate' },
  { id: uuidv4(), objectId: 'tkt-006', type: 'LIST_RESALE', actor: demoTickets[5].ownerWallet, timestamp: pastDate(2), status: 'completed', description: 'Ticket listed for resale at $749' },
  { id: uuidv4(), objectId: 'tkt-009', type: 'PURCHASE', actor: DEMO_CONSUMER_WALLET, timestamp: pastDate(0), status: 'completed', description: 'Purchased Flight + Champagne Picnic ticket' },
  { id: uuidv4(), objectId: 'tkt-009', type: 'VERIFY', actor: 'system', timestamp: pastDate(0), status: 'pending', description: 'Anchoring ticket to blockchain...' },
];

// ─── Stats ──────────────────────────────────────────────────────────

export const demoStats: DashboardStats = {
  totalEvents: demoEvents.length,
  activeEvents: demoEvents.filter(e => e.status === 'on-sale').length,
  totalTicketsSold: demoEvents.reduce((sum, e) => sum + e.tiers.reduce((ts, t) => ts + t.sold, 0), 0),
  totalRevenue: demoEvents.reduce((sum, e) => sum + e.tiers.reduce((ts, t) => ts + (t.sold * t.price), 0), 0),
  ticketsByStatus: {
    valid: 5,
    used: 1,
    transferred: 0,
    expired: 0,
    cancelled: 0,
    listed: 3,
  },
  revenueChange: '+18.2%',
  topEvent: 'Coachella 2026 — Weekend 1',
};

export { DEMO_CONSUMER_WALLET, DEMO_ADMIN_WALLET };
